### ISSUE TITLE
Implementing `alpha` (the baseline, no notion of transparency at all)

### ISSUE THREAD

**Issue by eubinean** [eubinecto/idiomify-demo#1]
## Why?

In order to test if the notion of transparency is helpful at all, we need to first build a model that cares only about the figurative meaning of idioms.

## To-do's
- [ ] first, implement `fetch_epie` as those are what you will be using after all.
- [ ] Choose the idioms (3 transparent, 3 opaque). 
- [ ] Build `wisdom2context` dataset

**Comment by eubinean** [comment]
## Implement `fetch_epie` 

## Choose the idioms

I need three transparent idioms, and three opaque ones. It'd be best if I those are all static idioms.
